# Generated by Django 4.1.6 on 2023-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessory_bottom_coat_shoe_top_delete_closet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='top',
            name='toptypes',
            field=models.ManyToManyField(to='main_app.toptype'),
        ),
    ]
