# Generated by Django 4.1.6 on 2023-02-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toptype_toy_top_toptypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessorytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bottomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Toy',
        ),
        migrations.AddField(
            model_name='accessory',
            name='accessorytypes',
            field=models.ManyToManyField(to='main_app.accessorytype'),
        ),
        migrations.AddField(
            model_name='bottom',
            name='bottomtypes',
            field=models.ManyToManyField(to='main_app.bottomtype'),
        ),
        migrations.AddField(
            model_name='coat',
            name='coattypes',
            field=models.ManyToManyField(to='main_app.coattype'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='shoetypes',
            field=models.ManyToManyField(to='main_app.shoetype'),
        ),
    ]
