# Generated by Django 4.1.6 on 2023-02-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_accessorytype_bottomtype_coattype_shoetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.top')),
            ],
        ),
    ]
