# Generated by Django 4.1.6 on 2023-02-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_topphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='toptypes',
        ),
        migrations.DeleteModel(
            name='Toptype',
        ),
    ]
