# Generated by Django 4.1.6 on 2023-02-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_top_toptypes_delete_toptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='accessorytypes',
        ),
        migrations.RemoveField(
            model_name='bottom',
            name='bottomtypes',
        ),
        migrations.RemoveField(
            model_name='coat',
            name='coattypes',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoetypes',
        ),
        migrations.DeleteModel(
            name='Accessorytype',
        ),
        migrations.DeleteModel(
            name='Bottomtype',
        ),
        migrations.DeleteModel(
            name='Coattype',
        ),
        migrations.DeleteModel(
            name='Shoetype',
        ),
    ]
