# Generated by Django 4.1.6 on 2023-02-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_accessory_accessorytypes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoephoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='Coatphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('coat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coat')),
            ],
        ),
        migrations.CreateModel(
            name='Bottomphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bottom')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoryphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.accessory')),
            ],
        ),
    ]
