# Generated by Django 4.1.6 on 2023-02-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_outfit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='occasion',
        ),
        migrations.AddField(
            model_name='outfit',
            name='occasion',
            field=models.ManyToManyField(to='main_app.style'),
        ),
    ]
