# Generated by Django 4.1.6 on 2023-02-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_occasion_outfit_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='style',
            new_name='styles',
        ),
    ]
