# Generated by Django 4.1.6 on 2023-02-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_style_outfit_styles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='styles',
            new_name='occasions',
        ),
    ]
