# Generated by Django 4.1.6 on 2023-02-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_styles_outfit_occasions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='occasions',
        ),
        migrations.AddField(
            model_name='style',
            name='outfit',
            field=models.ManyToManyField(to='main_app.outfit'),
        ),
    ]
