# Generated by Django 4.1.6 on 2023-02-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_outfit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='outfit',
            new_name='outfits',
        ),
    ]
